<MyRoot>:

    totaleGeld: totaleGeld

    BoxLayout:
        orientation: "vertical"
        Label:
            text: "SumupFactuur"
            font_size: 64
            color: 0.11, 0.24, 0.44
        Label:
            id: totaleGeld
            text: "-"
            font_size: 64
        Button:
            text: "Confirm"
            font_size: 32
            size: 100, 50
            on_press: root.getTransactions()